### ISSUE TITLE
ClassNotFoundException: org.netlib.blas.Dspmv

### ISSUE THREAD

**Issue by dprodanov** [sumit3203/ACTIVESEGMENTATION#49]
null
PT: SEGMENTATION
C:\Applications\ImageJ\plugins\jars\
home: C:\Applications\ImageJ\plugins\jars\
classpath:  C:\GitHub\ACTIVESEGMENTATION\.temp-Active_Segmentation_-classpathOnly-1582582604401.jar;C:\Applications\ImageJ\plugins\jars\arpack_combined.jar
classpath:  C:\GitHub\ACTIVESEGMENTATION\.temp-Active_Segmentation_-classpathOnly-1582582604401.jar;C:\Applications\ImageJ\plugins\jars\arpack_combined.jar;C:\Applications\ImageJ\plugins\jars\Auto_Threshold.jar
classpath:  C:\GitHub\ACTIVESEGMENTATION\.temp-Active_Segmentation_-classpathOnly-1582582604401.jar;C:\Applications\ImageJ\plugins\jars\arpack_combined.jar;C:\Applications\ImageJ\plugins\jars\Auto_Threshold.jar;C:\Applications\ImageJ\plugins\jars\BeanShell.jar
classpath:  C:\GitHub\ACTIVESEGMENTATION\.temp-Active_Segmentation_-classpathOnly-1582582604401.jar;C:\Applications\ImageJ\plugins\jars\arpack_combined.jar;C:\Applications\ImageJ\plugins\jars\Auto_Threshold.jar;C:\Applications\ImageJ\plugins\jars\BeanShell.jar;C:\Applications\ImageJ\plugins\jars\blas-0.8.jar
classpath:  C:\GitHub\ACTIVESEGMENTATION\.temp-Active_Segmentation_-classpathOnly-1582582604401.jar;C:\Applications\ImageJ\plugins\jars\arpack_combined.jar;C:\Applications\ImageJ\plugins\jars\Auto_Threshold.jar;C:\Applications\ImageJ\plugins\jars\BeanShell.jar;C:\Applications\ImageJ\plugins\jars\blas-0.8.jar;C:\Applications\ImageJ\plugins\jars\bsf-utils-3.1.jar
classpath:  C:\GitHub\ACTIVESEGMENTATION\.temp-Active_Segmentation_-classpathOnly-1582582604401.jar;C:\Applications\ImageJ\plugins\jars\arpack_combined.jar;C:\Applications\ImageJ\plugins\jars\Auto_Threshold.jar;C:\Applications\ImageJ\plugins\jars\BeanShell.jar;C:\Applications\ImageJ\plugins\jars\blas-0.8.jar;C:\Applications\ImageJ\plugins\jars\bsf-utils-3.1.jar;C:\Applications\ImageJ\plugins\jars\core.jar
classpath:  C:\GitHub\ACTIVESEGMENTATION\.temp-Active_Segmentation_-classpathOnly-1582582604401.jar;C:\Applications\ImageJ\plugins\jars\arpack_combined.jar;C:\Applications\ImageJ\plugins\jars\Auto_Threshold.jar;C:\Applications\ImageJ\plugins\jars\BeanShell.jar;C:\Applications\ImageJ\plugins\jars\blas-0.8.jar;C:\Applications\ImageJ\plugins\jars\bsf-utils-3.1.jar;C:\Applications\ImageJ\plugins\jars\core.jar;C:\Applications\ImageJ\plugins\jars\jackson-annotations-2.3.1.jar
classpath:  C:\GitHub\ACTIVESEGMENTATION\.temp-Active_Segmentation_-classpathOnly-1582582604401.jar;C:\Applications\ImageJ\plugins\jars\arpack_combined.jar;C:\Applications\ImageJ\plugins\jars\Auto_Threshold.jar;C:\Applications\ImageJ\plugins\jars\BeanShell.jar;C:\Applications\ImageJ\plugins\jars\blas-0.8.jar;C:\Applications\ImageJ\plugins\jars\bsf-utils-3.1.jar;C:\Applications\ImageJ\plugins\jars\core.jar;C:\Applications\ImageJ\plugins\jars\jackson-annotations-2.3.1.jar;C:\Applications\ImageJ\plugins\jars\jackson-core-2.3.1.jar
classpath:  C:\GitHub\ACTIVESEGMENTATION\.temp-Active_Segmentation_-classpathOnly-1582582604401.jar;C:\Applications\ImageJ\plugins\jars\arpack_combined.jar;C:\Applications\ImageJ\plugins\jars\Auto_Threshold.jar;C:\Applications\ImageJ\plugins\jars\BeanShell.jar;C:\Applications\ImageJ\plugins\jars\blas-0.8.jar;C:\Applications\ImageJ\plugins\jars\bsf-utils-3.1.jar;C:\Applications\ImageJ\plugins\jars\core.jar;C:\Applications\ImageJ\plugins\jars\jackson-annotations-2.3.1.jar;C:\Applications\ImageJ\plugins\jars\jackson-core-2.3.1.jar;C:\Applications\ImageJ\plugins\jars\jackson-databind-2.3.1.jar
classpath:  C:\GitHub\ACTIVESEGMENTATION\.temp-Active_Segmentation_-classpathOnly-1582582604401.jar;C:\Applications\ImageJ\plugins\jars\arpack_combined.jar;C:\Applications\ImageJ\plugins\jars\Auto_Threshold.jar;C:\Applications\ImageJ\plugins\jars\BeanShell.jar;C:\Applications\ImageJ\plugins\jars\blas-0.8.jar;C:\Applications\ImageJ\plugins\jars\bsf-utils-3.1.jar;C:\Applications\ImageJ\plugins\jars\core.jar;C:\Applications\ImageJ\plugins\jars\jackson-annotations-2.3.1.jar;C:\Applications\ImageJ\plugins\jars\jackson-core-2.3.1.jar;C:\Applications\ImageJ\plugins\jars\jackson-databind-2.3.1.jar;C:\Applications\ImageJ\plugins\jars\java-cup-0.11a.jar
classpath:  C:\GitHub\ACTIVESEGMENTATION\.temp-Active_Segmentation_-classpathOnly-1582582604401.jar;C:\Applications\ImageJ\plugins\jars\arpack_combined.jar;C:\Applications\ImageJ\plugins\jars\Auto_Threshold.jar;C:\Applications\ImageJ\plugins\jars\BeanShell.jar;C:\Applications\ImageJ\plugins\jars\blas-0.8.jar;C:\Applications\ImageJ\plugins\jars\bsf-utils-3.1.jar;C:\Applications\ImageJ\plugins\jars\core.jar;C:\Applications\ImageJ\plugins\jars\jackson-annotations-2.3.1.jar;C:\Applications\ImageJ\plugins\jars\jackson-core-2.3.1.jar;C:\Applications\ImageJ\plugins\jars\jackson-databind-2.3.1.jar;C:\Applications\ImageJ\plugins\jars\java-cup-0.11a.jar;C:\Applications\ImageJ\plugins\jars\javax.servlet-api-3.1.0.jar
classpath:  C:\GitHub\ACTIVESEGMENTATION\.temp-Active_Segmentation_-classpathOnly-1582582604401.jar;C:\Applications\ImageJ\plugins\jars\arpack_combined.jar;C:\Applications\ImageJ\plugins\jars\Auto_Threshold.jar;C:\Applications\ImageJ\plugins\jars\BeanShell.jar;C:\Applications\ImageJ\plugins\jars\blas-0.8.jar;C:\Applications\ImageJ\plugins\jars\bsf-utils-3.1.jar;C:\Applications\ImageJ\plugins\jars\core.jar;C:\Applications\ImageJ\plugins\jars\jackson-annotations-2.3.1.jar;C:\Applications\ImageJ\plugins\jars\jackson-core-2.3.1.jar;C:\Applications\ImageJ\plugins\jars\jackson-databind-2.3.1.jar;C:\Applications\ImageJ\plugins\jars\java-cup-0.11a.jar;C:\Applications\ImageJ\plugins\jars\javax.servlet-api-3.1.0.jar;C:\Applications\ImageJ\plugins\jars\jcommon-1.0.23.jar
classpath:  C:\GitHub\ACTIVESEGMENTATION\.temp-Active_Segmentation_-classpathOnly-1582582604401.jar;C:\Applications\ImageJ\plugins\jars\arpack_combined.jar;C:\Applications\ImageJ\plugins\jars\Auto_Threshold.jar;C:\Applications\ImageJ\plugins\jars\BeanShell.jar;C:\Applications\ImageJ\plugins\jars\blas-0.8.jar;C:\Applications\ImageJ\plugins\jars\bsf-utils-3.1.jar;C:\Applications\ImageJ\plugins\jars\core.jar;C:\Applications\ImageJ\plugins\jars\jackson-annotations-2.3.1.jar;C:\Applications\ImageJ\plugins\jars\jackson-core-2.3.1.jar;C:\Applications\ImageJ\plugins\jars\jackson-databind-2.3.1.jar;C:\Applications\ImageJ\plugins\jars\java-cup-0.11a.jar;C:\Applications\ImageJ\plugins\jars\javax.servlet-api-3.1.0.jar;C:\Applications\ImageJ\plugins\jars\jcommon-1.0.23.jar;C:\Applications\ImageJ\plugins\jars\jfreechart-1.0.19.jar
classpath:  C:\GitHub\ACTIVESEGMENTATION\.temp-Active_Segmentation_-classpathOnly-1582582604401.jar;C:\Applications\ImageJ\plugins\jars\arpack_combined.jar;C:\Applications\ImageJ\plugins\jars\Auto_Threshold.jar;C:\Applications\ImageJ\plugins\jars\BeanShell.jar;C:\Applications\ImageJ\plugins\jars\blas-0.8.jar;C:\Applications\ImageJ\plugins\jars\bsf-utils-3.1.jar;C:\Applications\ImageJ\plugins\jars\core.jar;C:\Applications\ImageJ\plugins\jars\jackson-annotations-2.3.1.jar;C:\Applications\ImageJ\plugins\jars\jackson-core-2.3.1.jar;C:\Applications\ImageJ\plugins\jars\jackson-databind-2.3.1.jar;C:\Applications\ImageJ\plugins\jars\java-cup-0.11a.jar;C:\Applications\ImageJ\plugins\jars\javax.servlet-api-3.1.0.jar;C:\Applications\ImageJ\plugins\jars\jcommon-1.0.23.jar;C:\Applications\ImageJ\plugins\jars\jfreechart-1.0.19.jar;C:\Applications\ImageJ\plugins\jars\mtj-1.0.4.jar
classpath:  C:\GitHub\ACTIVESEGMENTATION\.temp-Active_Segmentation_-classpathOnly-1582582604401.jar;C:\Applications\ImageJ\plugins\jars\arpack_combined.jar;C:\Applications\ImageJ\plugins\jars\Auto_Threshold.jar;C:\Applications\ImageJ\plugins\jars\BeanShell.jar;C:\Applications\ImageJ\plugins\jars\blas-0.8.jar;C:\Applications\ImageJ\plugins\jars\bsf-utils-3.1.jar;C:\Applications\ImageJ\plugins\jars\core.jar;C:\Applications\ImageJ\plugins\jars\jackson-annotations-2.3.1.jar;C:\Applications\ImageJ\plugins\jars\jackson-core-2.3.1.jar;C:\Applications\ImageJ\plugins\jars\jackson-databind-2.3.1.jar;C:\Applications\ImageJ\plugins\jars\java-cup-0.11a.jar;C:\Applications\ImageJ\plugins\jars\javax.servlet-api-3.1.0.jar;C:\Applications\ImageJ\plugins\jars\jcommon-1.0.23.jar;C:\Applications\ImageJ\plugins\jars\jfreechart-1.0.19.jar;C:\Applications\ImageJ\plugins\jars\mtj-1.0.4.jar;C:\Applications\ImageJ\plugins\jars\mtj.jar
classpath:  C:\GitHub\ACTIVESEGMENTATION\.temp-Active_Segmentation_-classpathOnly-1582582604401.jar;C:\Applications\ImageJ\plugins\jars\arpack_combined.jar;C:\Applications\ImageJ\plugins\jars\Auto_Threshold.jar;C:\Applications\ImageJ\plugins\jars\BeanShell.jar;C:\Applications\ImageJ\plugins\jars\blas-0.8.jar;C:\Applications\ImageJ\plugins\jars\bsf-utils-3.1.jar;C:\Applications\ImageJ\plugins\jars\core.jar;C:\Applications\ImageJ\plugins\jars\jackson-annotations-2.3.1.jar;C:\Applications\ImageJ\plugins\jars\jackson-core-2.3.1.jar;C:\Applications\ImageJ\plugins\jars\jackson-databind-2.3.1.jar;C:\Applications\ImageJ\plugins\jars\java-cup-0.11a.jar;C:\Applications\ImageJ\plugins\jars\javax.servlet-api-3.1.0.jar;C:\Applications\ImageJ\plugins\jars\jcommon-1.0.23.jar;C:\Applications\ImageJ\plugins\jars\jfreechart-1.0.19.jar;C:\Applications\ImageJ\plugins\jars\mtj-1.0.4.jar;C:\Applications\ImageJ\plugins\jars\mtj.jar;C:\Applications\ImageJ\plugins\jars\pentaho-package-manager-1.0.8.jar
classpath:  C:\GitHub\ACTIVESEGMENTATION\.temp-Active_Segmentation_-classpathOnly-1582582604401.jar;C:\Applications\ImageJ\plugins\jars\arpack_combined.jar;C:\Applications\ImageJ\plugins\jars\Auto_Threshold.jar;C:\Applications\ImageJ\plugins\jars\BeanShell.jar;C:\Applications\ImageJ\plugins\jars\blas-0.8.jar;C:\Applications\ImageJ\plugins\jars\bsf-utils-3.1.jar;C:\Applications\ImageJ\plugins\jars\core.jar;C:\Applications\ImageJ\plugins\jars\jackson-annotations-2.3.1.jar;C:\Applications\ImageJ\plugins\jars\jackson-core-2.3.1.jar;C:\Applications\ImageJ\plugins\jars\jackson-databind-2.3.1.jar;C:\Applications\ImageJ\plugins\jars\java-cup-0.11a.jar;C:\Applications\ImageJ\plugins\jars\javax.servlet-api-3.1.0.jar;C:\Applications\ImageJ\plugins\jars\jcommon-1.0.23.jar;C:\Applications\ImageJ\plugins\jars\jfreechart-1.0.19.jar;C:\Applications\ImageJ\plugins\jars\mtj-1.0.4.jar;C:\Applications\ImageJ\plugins\jars\mtj.jar;C:\Applications\ImageJ\plugins\jars\pentaho-package-manager-1.0.8.jar;C:\Applications\ImageJ\plugins\jars\weka-dev-3.9.2.jar
java.lang.ClassNotFoundException: org.netlib.blas.Dspmv
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at activeSegmentation.filterImpl.FilterManager.loadFilters(FilterManager.java:135)
	at activeSegmentation.filterImpl.FilterManager.<init>(FilterManager.java:93)
	at activeSegmentation.filterImpl.FilterPanel.<init>(FilterPanel.java:95)
	at activeSegmentation.gui.Gui.doAction(Gui.java:68)
	at activeSegmentation.gui.Gui$1.actionPerformed(Gui.java:138)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by dprodanov** [comment]
The issue was caused by a bug in class loading.
