### ISSUE TITLE
Regresssion in loading classifiers

### ISSUE THREAD

**Issue by dprodanov** [sumit3203/ACTIVESEGMENTATION#50]
null
WARNING: core mtj jar files are not available as resources to this classloader (sun.misc.Launcher$AppClassLoader@6d06d69c)
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: no/uib/cipr/matrix/Matrix
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at weka.core.WekaPackageClassLoaderManager.forName(WekaPackageClassLoaderManager.java:198)
	at weka.core.WekaPackageClassLoaderManager.forName(WekaPackageClassLoaderManager.java:178)
	at weka.core.ClassDiscovery.find(ClassDiscovery.java:247)
	at weka.gui.GenericPropertiesCreator.generateOutputProperties(GenericPropertiesCreator.java:542)
	at weka.gui.GenericPropertiesCreator.execute(GenericPropertiesCreator.java:639)
	at weka.gui.GenericPropertiesCreator.<clinit>(GenericPropertiesCreator.java:167)
	at weka.core.WekaPackageManager.refreshGOEProperties(WekaPackageManager.java:1403)
	at weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1328)
	at weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1205)
	at weka.gui.GenericObjectEditor.determineClasses(GenericObjectEditor.java:172)
	at weka.gui.GenericObjectEditor.<clinit>(GenericObjectEditor.java:242)
	at activeSegmentation.gui.LearningPanel.<init>(LearningPanel.java:62)
	at activeSegmentation.gui.Gui.doAction(Gui.java:87)
	at activeSegmentation.gui.Gui$1.actionPerformed(Gui.java:138)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: no.uib.cipr.matrix.Matrix
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 52 more

**Comment by dprodanov** [comment]
Look at
https://stackoverflow.com/questions/42178995/weka-linear-regression-classnotfoundexception

I have solved it in the Bordeaux branch.

**Comment by dprodanov** [comment]
seems resolved by the latest commits.
